spring.application.name=demo

# MySQL接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=

# SQLをログに表示
spring.jpa.show-sql=true

# schema.sql と data.sql を実行する
spring.sql.init.mode=always

# Hibernateが schema.sql 実行後に初期化されるようにする
spring.jpa.defer-datasource-initialization=true