DROP TABLE IF EXISTS product;

CREATE TABLE product (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  price INT
);

CREATE TABLE orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  productId BIGINT,
  quantity INT
  order_date DATETIME
);